/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  OwnedUpgradeabilityStorage,
  OwnedUpgradeabilityStorageInterface,
} from "../OwnedUpgradeabilityStorage";

const _abi = [
  {
    inputs: [],
    name: "upgradeabilityOwner",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

const _bytecode =
  "0x6080604052348015600f57600080fd5b50608280601d6000396000f3fe6080604052348015600f57600080fd5b506004361060285760003560e01c80636fde820214602d575b600080fd5b600154604080516001600160a01b039092168252519081900360200190f3fea264697066735822122064defc1abd4053d935df15bae76171256b52ec411a86a322e47c0ba7909ddbb164736f6c634300080b0033";

type OwnedUpgradeabilityStorageConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: OwnedUpgradeabilityStorageConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class OwnedUpgradeabilityStorage__factory extends ContractFactory {
  constructor(...args: OwnedUpgradeabilityStorageConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<OwnedUpgradeabilityStorage> {
    return super.deploy(overrides || {}) as Promise<OwnedUpgradeabilityStorage>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): OwnedUpgradeabilityStorage {
    return super.attach(address) as OwnedUpgradeabilityStorage;
  }
  connect(signer: Signer): OwnedUpgradeabilityStorage__factory {
    return super.connect(signer) as OwnedUpgradeabilityStorage__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): OwnedUpgradeabilityStorageInterface {
    return new utils.Interface(_abi) as OwnedUpgradeabilityStorageInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): OwnedUpgradeabilityStorage {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as OwnedUpgradeabilityStorage;
  }
}
